FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# AORTA Message Broker Receiving Messages Rest

Aorta Rest is a simple API allowing tasks to be routed and medical messages to be transferred.

List of services that will be called on the AortaMessageBroker application:

 - Process Request - Task Management Application
   - Create a Process Request               POST   http://aorta:443/api/processrequests
   - Delete a Process Request               DELETE http://aorta:443/api/processrequests/123456
   - Update a Process Request               PUT    http://aorta:443/api/processrequests/123456

 - Tasks - Dynamic Scheduling Application
   - Create a Task                       POST   http://aorta:443/api/tasks
   - Delete a Task                       DELETE http://aorta:443/api/tasks/123456
   - Update a Task                       PUT    http://aorta:443/api/tasks/123456

## Process Requests Collection [/api/processrequests]

The collection of messages that deals with Process Requests.
Process Requests are used as input to create one or multiple tasks.

**POST requests**
 - First request: This message creates a process request.

**POST responses**
 - First POST response: HTTP 1/1 202 Accepted. AortaMessageBroker has been able to parse, route and distribute the message.
 - Second POST response: HTTP 1/1 400 Bad Request, with specific body (see below). AortaMessageBroker was not able to correctly parse the message.
 - Third POST response: HTTP 1/1 404 Not Found, with specific body (see below). AortaMessageBroker was not able to correctly route the message.
 - Fourth POST response: HTTP 1/1 500 Internal Server Error, with specific body (see below). AortaMessageBroker was not able to correctly process the message.

**DELETE requests**
 - First DELETE request: This message deletes a process request.

**PUT requests**
 - Third PUT request: This message updates a process request.
 
### Create a Process Request [POST]

+ Request (application/json)

        {
            "MessageType": "CreateProcessRequest",
            "ProcessRequest": {
                "Id": "a6baa2d8-03c8-4743-8f9a-ba633ba0d0e6",
                "CreationTime": "20160310.123456.123",
                "Creator": {
                    "Id": "696f236c-4cd4-4543-92af-8b5db60de3d3",
                    "Type": "Person",
                    "FirstName": "Dirk",
                    "LastName": "Dierickx",
                    "Roles": [
                        {   "Role": "Nurse" }
                    ]
                },
                "Objects": {
                    "Id": "52a39c42-3e69-4940-a348-49bd93790eda",
                    "FirstName": "Pieter",
                    "LastName": "Pieters",
                    "IdentificationMethods": [
                        {   "IdentificationMethod": "Wristband" },
                        {   "IdentificationMethod": "Username" }
                    ],
                    "Location": {
                        "Id": "cf12ce64-3080-4306-b3eb-daf9da8ac373",
                        "Name": "ReceptionBooth1",
                        "Description": "The blue one",
                        "Coordinates": "x;y;z"
                    },
                    "Roles": [
                        {   "Role": "Patient" }
                    ]
                },
                "StartLocation": {
                    "Id": "cf12ce64-3080-4306-b3eb-daf9da8ac373",
                    "Name": "ReceptionBooth1",
                    "Description": "The blue one",
                    "Coordinates": "x;y;z"
                },
                "EndLocation": {
                    "Id": "a73b7ba2-5a11-4568-9088-5a6326115697",
                    "Name": "Room 123",
                    "Description": "The oval office",
                    "Coordinates": "a;b;c"
                },
                "ProposedStartTime": "20150217.234826.780",
                "ProposedStartTimeWindow": {
                    "TimeWindowStart": "20150217.234501.780",
                    "TimeWindowEnd": "20150217.235401.780"
                },
                "ProposedEndTime": "20150218.012345.780",
                "ProposedEndTimeWindow": {
                    "TimeWindowStart": "20150218.001234.780",
                    "TimeWindowEnd": "20150218.123456.780"
                },
                "Status": "Requested",
                "Priority": "Normal",
                "Description": "Aanvraag voor transport op dinsdag, 17-feb-2015 rond 23:48 van patient Pieter Pieters van ontvangstbalie 1 naar kamer 123",                
                "Mode": "Enabled",
                "DisplayName": "Incoming patient to room",
                "Annotations": [
                    {   "CreationTime": "20150217.133456.780",
                        "Creator": "8d8e96ce-74c6-4dd4-94d6-15af724d6215",
                        "Value": "To schedule via blue path" }
                ]
            }
        }

+ Response 202 (application/json)

    + Headers

            Location: /api/processrequests/123456

    + Body
    
            {
                "AortaMessageBrokerInputResponse": "Accepted"
            }

+ Response 400 (application/json)

    + Headers

            Location: /api/processrequests/123456

    + Body
    
            {
                "AortaMessageBrokerInputResponse": "Parsing Error"
            }

+ Response 404 (application/json)

    + Headers

            Location: /api/processrequests/123456

    + Body
    
            {
                "AortaMessageBrokerInputResponse": "Routing Error"
            }

+ Response 500 (application/json)

    + Headers

            Location: /api/processrequests/123456

    + Body
    
            {
                "AortaMessageBrokerInputResponse": "Server Error"
            }

### Delete a Process Request [DELETE]

+ Response 202 (application/json)

### Update a Process Request [PUT]

+ Response 202 (application/json)

## Tasks Collection [/api/tasks]

The collection of messages that deals with Tasks. Tasks are actions that need to be performed by a person.

**POST requests**
 - First POST request: This message creates a task.

**POST responses**
 - First POST response: HTTP 1/1 202 Accepted. AortaMessageBroker has been able to parse, route and distribute the message.
 - Second POST response: HTTP 1/1 400 Bad Request, with specific body (see below). AortaMessageBroker was not able to correctly parse the message.
 - Third POST response: HTTP 1/1 404 Not Found, with specific body (see below). AortaMessageBroker was not able to correctly route the message.
 - Fourth POST response: HTTP 1/1 500 Internal Server Error, with specific body (see below). AortaMessageBroker was not able to correctly process the message.

**DELETE requests**
 - First DELETE request: This message deletes a task.

**PUT requests**
 - First PUT request: This message updates a task.
 
### Create a Task [POST]

+ Request (application/json)

        {
            "MessageType": "CreateTask",
            "Task": {
                "Id": "a6baa2d8-03c8-4743-8f9a-ba633ba0d0e6",
                "ProcessRequestId": "aeb7d11b-5588-4de7-822e-bd4a94da4df7",
                "CreationTime": "20160310",
                "Creator": {
                    "Id": "92ee3b32-14e2-40ea-b2f2-6b4c6a08b3d3",
                    "Type": "System",
                    "FirstName": "Scheduling Application",
                    "LastName": ""
                },
                "Subject": {
                    "Id": "52a39c42-3e69-4940-a348-49bd93790eda",
                    "FirstName": "Jan",
                    "LastName": "Janssens",
                    "IdentificationMethods": [
                        {   "IdentificationMethod": "Wearable" },
                        {   "IdentificationMethod": "DECT" }
                    ],
                    "Location": {
                        "Id": "cf12ce64-3080-4306-b3eb-daf9da8ac373",
                        "Name": "ReceptionBooth1",
                        "Description": "The blue one",
                        "Coordinates": "x;y;z"
                    },
                    "Roles": [
                        {   "Role": "Nurse" }
                    ],
                    "Devices": [
                        {   "Device": "Wearable",
                            "Type": "A5" },
                        {   "Device": "DECT",
                            "Type": "Siemens" }
                    ],
                    "Competences": [
                        {   "Competence": "CarryAbility",
                            "Type": "Transport",
                            "Limit": "10 kg" },
                        {   "Competence": "French",
                            "Type": "Language",
                            "Level": "Good" }
                    ]
                },
                "TaskType": "PatientTransport",
                "Objects": [],
                "StartLocation": {
                    "Id": "cf12ce64-3080-4306-b3eb-daf9da8ac373",
                    "Name": "ReceptionBooth1",
                    "Description": "The blue one",
                    "Coordinates": "x;y;z"
                },
                "EndLocation": {
                    "Id": "a73b7ba2-5a11-4568-9088-5a6326115697",
                    "Name": "Room 123",
                    "Description": "The oval office",
                    "Coordinates": "a;b;c"
                },
                "ResponseDeadline": "20150217.234826.780",
                "Preconditions": [],
                "Actions": [
                    {   "Id": "0ca435c7-ad1b-44fd-8f34-a1aa174fd888",
                        "ActionType": "Pickup",
                        "Subject": {
                            "Id": "52a39c42-3e69-4940-a348-49bd93790eda",
                            "FirstName": "Peter",
                            "LastName": "Jans",
                            "IdentificationMethods": [
                                {   "IdentificationMethod": "Wearable" },
                                {   "IdentificationMethod": "DECT" }
                            ],
                            "Location": {
                                "Id": "cf12ce64-3080-4306-b3eb-daf9da8ac373",
                                "Name": "ReceptionBooth1",
                                "Description": "The blue one",
                                "Coordinates": "x;y;z"
                            },
                            "Roles": [
                                {   "Role": "ManOfManyTrades" },
                                {   "Role": "Hospic" }
                            ],
                            "Devices": [
                                {   "Device": "Wearable",
                                    "Type": "A5" },
                                {   "Device": "DECT",
                                    "Type": "Siemens" }
                            ],
                            "Competences": [
                                {   "Competence": "CarryAbility",
                                    "Type": "Transport",
                                    "Limit": "10 kg" },
                                {   "Competence": "French",
                                    "Type": "Language",
                                    "Level": "Good" }
                            ]
                        },
                        "StartLocation": {
                            "Id": "cf12ce64-3080-4306-b3eb-daf9da8ac373",
                            "Name": "RestRoom1",
                            "Description": "The old one",
                            "Coordinates": "x;y;z"
                        },
                        "EndLocation": {
                            "Id": "a73b7ba2-5a11-4568-9088-5a6326115697",
                            "Name": "ReceptionBooth7",
                            "Description": "The blue one",
                            "Coordinates": "a;b;c"
                        },                        "": "",
                        "EffectiveStartTime": "",
                        "EffectiveEndTime": "",
                        "Preconditions": [],
                        "Status": "Requested",
                        "Priority": "Normal",
                        "Description": "Pick up patient at Reception"
                    },
                    {   "Id": "177114d8-a8eb-48e5-9d38-fe7cdf945d8f",
                        "ActionType": "Delivery",
                        "Subject": {
                            "Id": "52a39c42-3e69-4940-a348-49bd93790eda",
                            "FirstName": "Peter",
                            "LastName": "Jans",
                            "IdentificationMethods": [
                                {   "IdentificationMethod": "Wearable" },
                                {   "IdentificationMethod": "DECT" }
                            ],
                            "Location": {
                                "Id": "cf12ce64-3080-4306-b3eb-daf9da8ac373",
                                "Name": "ReceptionBooth1",
                                "Description": "The blue one",
                                "Coordinates": "x;y;z"
                            },
                            "Roles": [
                                {   "Role": "ManOfManyTrades" },
                                {   "Role": "Hospic" }
                            ],
                            "Devices": [
                                {   "Device": "Wearable",
                                    "Type": "A5" },
                                {   "Device": "DECT",
                                    "Type": "Siemens" }
                            ],
                            "Competences": [
                                {   "Competence": "CarryAbility",
                                    "Type": "Transport",
                                    "Limit": "10 kg" },
                                {   "Competence": "French",
                                    "Type": "Language",
                                    "Level": "Good" }
                            ]
                        },
                        "StartLocation": {
                            "Id": "a73b7ba2-5a11-4568-9088-5a6326115697",
                            "Name": "ReceptionBooth7",
                            "Description": "The blue one",
                            "Coordinates": "a;b;c"
                        },
                        "EndLocation": {
                            "Id": "1be31714-b995-4dfe-80a0-3eede25c5d10",
                            "Name": "Room 123",
                            "Description": "The oval office",
                            "Coordinates": "a;b;c"
                        },                        "": "",
                        "EffectiveStartTime": "",
                        "EffectiveEndTime": "",
                        "Preconditions": [],
                        "Status": "Requested",
                        "Priority": "Normal",
                        "Description": "Deliver a patient to his room"
                    }
                ],
                "Status": "Requested",
                "Priority": "Normal",
                "Description": "Pick up patient at Reception",
                "Mode": "Enabled",
                "DisplayName": "Incoming patient to room",
                "Annotations": [
                    {   "CreationTime": "20150217.133456.780",
                        "Creator": "8d8e96ce-74c6-4dd4-94d6-15af724d6215",
                        "Value": "Scheduled via blue pathway" }
                ]
            }
        }

+ Response 202 (application/json)

    + Headers

            Location: /api/tasks/123456

    + Body
    
            {
                "AortaMessageBrokerOutputResponse": "Accepted"
            }

+ Response 400 (application/json)

    + Headers

            Location: /api/tasks/123456

    + Body
    
            {
                "AortaMessageBrokerOutputResponse": "Parsing Error"
            }

+ Response 404 (application/json)

    + Headers

            Location: /api/tasks/123456

    + Body
    
            {
                "AortaMessageBrokerOutputResponse": "Routing Error"
            }

+ Response 500 (application/json)

    + Headers

            Location: /api/tasks/123456

    + Body
    
            {
                "AortaMessageBrokerInputResponse": "Server Error"
            }

### Delete a Task [DELETE]

+ Response 202 (application/json)

### Update a Task [PUT]

+ Response 202 (application/json)